repos:
- repo: https://github.com/sourcery-ai/sourcery
  rev: v1.36.0
  hooks:
  - id: sourcery
    # The best way to use Sourcery in a pre-commit hook:
    # * review only changed lines:
    # * omit the summary
    args: [--diff=git diff HEAD, --no-summary]

- repo: https://github.com/koalaman/shellcheck-precommit
  rev: v0.9.0
  hooks:
  - id: shellcheck
    args: ["--severity=warning"]  # Enforce warnings and errors
    stages: [manual]  # Skip during normal commits

- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
  - id: shfmt
    args: ["-i", "4", "-ci", "-bn"]  # Use 4 spaces for indentation, indent case statements
    stages: [manual]  # Skip during normal commits

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
    args: ['--maxkb=500']
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
