const fs = require('fs');
const path = require('path');

describe('Project Directory Structure Validation', () => {
  const projectRoot = path.join(__dirname, '..', '..');

  test('Root directory should contain expected main files and directories', () => {
    const rootContents = fs.readdirSync(projectRoot).sort();
    const expectedRootContents = [
      'bin', 'lib', 'modules', 'scripts', 'tests',
      'docs', 'package.json', 'package-lock.json',
      'README.md', 'CHANGELOG.md', 'COMPREHENSIVE_CODE_REVIEW.md',
      'jest.config.js', 'jest.config.enhanced.js', 'Dockerfile',
      'eslint.config.js'
    ].sort();

    expectedRootContents.forEach(expectedItem => {
      expect(rootContents).toContain(expectedItem);
    });
  });

  test('bin/ directory should contain the main script', () => {
    const binPath = path.join(projectRoot, 'bin');
    expect(fs.existsSync(binPath)).toBe(true);
    expect(fs.existsSync(path.join(binPath, 'uninstall_cursor.sh'))).toBe(true);
  });

  test('lib/ directory should contain essential library files', () => {
    const libPath = path.join(projectRoot, 'lib');
    const libContents = fs.readdirSync(libPath).sort();
    // Updated to include actual current structure
    const expectedLibContents = [
      'ai', 'cache', 'config.sh', 'error_codes.sh', 'helpers.sh',
      'lang', 'shadow', 'ui', 'ui.sh'
    ].sort();
    expect(libContents).toEqual(expectedLibContents);
  });

  test('modules/ directory should contain functional modules', () => {
    const modulesPath = path.join(projectRoot, 'modules');
    const modulesContents = fs.readdirSync(modulesPath).sort();
    // Updated to include actual current structure
    const expectedModulesContents = [
      'ai_optimization.sh',
      'complete_removal.sh',
      'git_integration.sh',
      'installation.sh',
      'integration',
      'optimization.sh',
      'performance',
      'uninstall.sh'
    ].sort();
    expect(modulesContents).toEqual(expectedModulesContents);
  });

  test('scripts/ directory should contain expected utility scripts and resume-creation/', () => {
    const scriptsPath = path.join(projectRoot, 'scripts');
    const actualScriptsContents = fs.readdirSync(scriptsPath).sort();
    // Updated to include actual current structure
    const expectedScriptsContents = [
      'build_release.sh',
      'create_dmg_package.sh',
      'install_cursor_uninstaller.sh',
      'optimize_system.sh',
      'resume-creation',
      'setup.sh',
      'syntax_and_shellcheck.sh',
      'verify.sh',
      'verify_simple.sh'
    ].sort();
    expect(actualScriptsContents).toEqual(expectedScriptsContents);
  });

  test('No development artifacts should remain in root', () => {
    const rootContents = fs.readdirSync(projectRoot);
    // Updated to allow coverage directory since it's generated by tests
    const bannedItems = ['node_modules_backup', 'dist', 'build', '.env.local', 'debug.log'];

    bannedItems.forEach(bannedItem => {
      expect(rootContents).not.toContain(bannedItem);
    });
  });

  test('Essential documentation files should exist', () => {
    const docFiles = ['README.md', 'CHANGELOG.md'];

    docFiles.forEach(docFile => {
      const filePath = path.join(projectRoot, docFile);
      expect(fs.existsSync(filePath)).toBe(true);
    });
  });
}); 